version: '3.8'

services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: user_service:local
    container_name: user_service
    env_file:
      - ./.env
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/hng_database
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn base.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - user_net
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: user_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hng_database
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - user_net
    restart: unless-stopped

volumes:
  user_pgdata:

networks:
  user_net:
    driver: bridge
